[package]
name = "manganese"
version = "1.0.0"
edition = "2021"
rust-version = "1.80"

[[bin]]
name = "manganese"
path = "src/main.rs"

[dependencies]
rayon = "1.11.0"
cfg-if = "1.0.4"
num_cpus = "1.17.0"
glob = "0.3.3"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32", "Win32_System", "Win32_System_SystemInformation"] }
serde = { version = "1.0.228", features = ["derive"] }
winapi = { version = "0.3", features = ["winbase", "sysinfoapi", "memoryapi", "processthreadsapi", "handleapi", "winnt"] }

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.178"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[features]
default = []
avx2 = []
avx512f = []

