[build]
rustflags = [
    "-C", "target-cpu=x86-64-v4",
    "-C", "target-feature=+avx2,+avx512f,+avx512bw",
    # see: rustc --print target-cpus ; e.g. x86-64, x86-64-v3, x86-64-v4, znver3, znver5
    # see: https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels
    # alternatively for avx256 support only:
    #"-C", "target-cpu=x86-64-v3",
    #"-C", "target-feature=+avx2,+fma",
]